//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeRFDemo.Effects
{
    using Evergine.Common.Graphics;
    using Evergine.Framework.Graphics;
    using Evergine.Framework.Graphics.Effects;
    using Evergine.Mathematics;
    
    
    [Evergine.Framework.Graphics.MaterialDecoratorAttribute("3d5cf3bb-c89b-4259-8a26-68ea428c98d9")]
    public partial class FullQuad : Evergine.Framework.Graphics.MaterialDecorator
    {
        
        public FullQuad(Evergine.Framework.Graphics.Effects.Effect effect) : 
                base(new Material(effect))
        {
        }
        
        public FullQuad(Evergine.Framework.Graphics.Material material) : 
                base(material)
        {
        }
        
        public Evergine.Common.Graphics.Texture Input
        {
            get
            {
                return this.material.TextureSlots[0].Texture;
            }
            set
            {
				this.material.SetTexture(value, 0);
            }
        }
        
        public Evergine.Common.Graphics.SamplerState Sampler
        {
            get
            {
                return this.material.SamplerSlots[0].Sampler;
            }
            set
            {
				this.material.SetSampler(value, 0);
            }
        }
    }
}
